### ISSUE TITLE
RFC: Abstracting over the backend

### ISSUE THREAD

**Issue by cocreature** [tdammers/yeshql#3]
Currently yeshql generates queries for `HDBC`. While `HDBC` supports a lot of databases or probably due to that its support for database specific features (I’m specifically interested in `PostgreSQL`) is relatively limited, e.g. custom data types are not supported.

Of course it would be possible to implement `yeshql-postgresql-simple` or `yeshql-hasql` as completely separate packages, a lot of the code in `yeshql` actually doesn’t care about what backend is being used and it seems to be possible to abstract over the backend such that users can choose how exactly they want to generate queries.

I’d be interested in implementing this but to avoid spending time on it only for it to be rejected, I’m opening this issue to ask whether you would be interested in seeing this in `yeshql`? If so any specific ideas on the direction this should take or should I just make an initial implementation and then we can iterate on that?

**Comment by tdammers** [comment]
First of all, love the idea. HDBC is perfectly adequate for my needs, but I can absolutely see a use case for combining yeshql with other backends.

The way I see it, there is an obvious approach to this, namely, splitting up `yeshql` into `yeshql-core` (containing the parser and the AST), and a collection of backend-specific packages `yeshql-hdbc`, `yeshql-postgresql-simple`, etc., each of them depending on `yeshql-core` and providing a backend-specific version of the current `yeshql` API (i.e., the `yesh...` family of functions. So `Database.YeshQL.HDBC.yesh` would generate `HDBC` functions, `Database.YeshQL.PostgresqlSimple.yesh` would generate `postgresql-simple` functions, etc.; but they would all use the same parser and AST.

Going from the current situation to one where there is just one supported backend package would be a logistic operation more than anything; the most important decision here would, IMHO, be whether `yeshql` should become a monorepo with both `yeshql-core` and `yeshql-hdbc` in it, or whether `yeshql-hdbc` should be split off into a separate repo. I'm currently leaning slightly towards the monorepo approach, but I'm open to anything.

Either way, I think the best way forward would be for me to perform the splitting, and then you could take `yeshql-hdbc` as a template for `yeshql-postgresql-simple`.

**Comment by cocreature** [comment]
Sounds good, let me know if I can be of help! I’m generally in favor of a monorepo as well.

**Comment by tdammers** [comment]
Alright, here's what the split version looks like:

https://github.com/tdammers/yeshql/tree/rfc-separate-backends

AFAICT, everything works. Ideally, I think there should be a "legacy" package that forms a backwards-compatible shim over `yeshql-core` and `yeshql-hdbc`, which shouldn't be a big deal, just a matter of pulling in the dependencies and appropriately re-exporting things. Grunt work, basically, which is why I haven't done it yet.

I've split up the `Database.YeshQL` module; the HDBC-specific parts have moved to `Database.YeshQL.HDBC` in the `-hdbc` package, the rest to `Database.YeshQL.Util`, because I feel other backends will want to reuse those. I'm not 100% sure whether there may be other things that need to move to `Util`, I guess we'll find out when we implement other backends.

**Comment by cocreature** [comment]
Wow, that was fast! I’ll take a stab at a `postgresql-simple` backend over the weekend.

**Comment by tdammers** [comment]
Look like this is solved now.
