### ISSUE TITLE
Does yeshql really support () return type

### ISSUE THREAD

**Issue by noxecane** [tdammers/yeshql#8]
**Expected**
```haskell
[yesh|
  -- name: testMe :: ()
  -- :name :: String
  insert into tables(name) values(:name);
|]
testMe :: Connection -> String -> IO ()
```
**Actual**
Haskell Error
```
 • Couldn't match type ‘Maybe a0’ with ‘()’
      Expected type: IO ()
        Actual type: IO (Maybe a0)
    • In the expression:
        (((\ qstr_aCmA params_aCmB conn_aCmC
             -> (fmap yeshql-core-4.1.0.1:Database.YeshQL.Util.headMay)
                  (((Database.PostgreSQL.Simple.query conn_aCmC)
                      (Data.String.fromString qstr_aCmA))
                     params_aCmB))
            "  insert into tables(name) values(?);
```

Note that the original statement I did this on is an insert statement that returns nothing. So this is most probably not because of a select statement.

**Comment by tdammers** [comment]
It may be worth noting that the type annotations used in yeshql syntax aren't proper Haskell syntax.

Parentheses mean "return results as a tuple" (i.e., marshal each column to a tuple element), whereas return types without parentheses means yeshql should marshal each row to a single value. And further, queries generally return either a list or a `Maybe`. So in principle, declaring `()` as the return type means you want a `Maybe` of a 0-tuple. A 0-tuple should, in principle, be `()`, so I'll dive into why it doesn't resolve to that, but the `Maybe` is accurate.

Note, further, that yeshql knows absolutely nothing about SQL syntax, it cannot tell a `SELECT` query from an `INSERT` query - by design, yeshql treats queries more or less as opaque strings. However, there is a way to tell it to not try to read any result sets, but instead get the "rows affected" count, and return that as something integral: declare the return type as `rowcount Integer` (or `rowcount Int`, or whatever integer type you want). Checking this counter is good practice anyway, and I tend to always do it, which is probably why this hasn't popped up before.

So I'll take a look, though I'm not sure whether I can find the time this weekend.

**Comment by noxecane** [comment]
The function/statement that needed this actually ignores results by design(unique exceptions  are ignored). But I ended up using `returning id;` and then composing the original function with `const (return ())`.

**Comment by tdammers** [comment]
Hmm, but yeshql doesn't really care what's inside the query string, so `returning id` is not going to make any difference whatsover. You could do the following, and it would compile:

```haskell
[yesh|
  -- name: testMe :: (Int)
  blargh blob bloop bleep
|]
```

I've taken a quick look at the code, and it seems that declaring a return type of `()` should, in principle, compile to `-> IO ()`, at least for the `HDBC` and `PostgreSQL` backends in the most recent version. It's possible though that older versions didn't special-case the "0-tuple return type" case, in which case you would get `-> IO (Maybe ())`.

**Comment by noxecane** [comment]
I assumed that the definition of the generated function is correct. The error seems to be pointing out that the code
```haskell
(((\qstr_aCmA params_aCmB conn_aCmC
             -> (fmap yeshql-core-4.1.0.1:Database.YeshQL.Util.headMay)
                  (((Database.PostgreSQL.Simple.query conn_aCmC)
                      (Data.String.fromString qstr_aCmA))
                     params_aCmB))
            "  insert into tables(name) values(?);"
```
returns a `Maybe`, rather than the declared `()`. Perhaps I'll deal with it later when I finally get to understand QuasiQuoting. 
By the way I am using `v4.1.0.1`, the latest version

**Comment by tdammers** [comment]
Did some more digging, turns out it's an outright blatant bug.

When you declare `()` as the return type, YeshQL is supposed to do exactly what you expected originally: ignore any and all results, just run the query and return `()`. In order to do that, the TH code generator needs to generate two things: a type for the query function, and a function body - and while it generates the correct type (something of type `... -> IO ()`), the body it generates doesn't typecheck.

**Comment by noxecane** [comment]
Thanks a lot. I am going to download this as soon as I can. Turns out my solution hides SqlExceptions.

**Comment by noxecane** [comment]
So some strange behaviour that I can live with, it's this
```haskell
*** Exception: QueryError {qeMessage = "", qeQuery = "  insert into a_b(a, b)\n  values (?, ?);\n"}
```
And this when I use returning id(it was supposed to ignore it).
```haskell
*** Exception: Incompatible {errSQLType = "int4", errSQLTableOid = Just (Oid 17519), errSQLField = "id", errHaskellType = "()", errMessage = ""}
```
